# Generated by Django 3.1.4 on 2021-02-25 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210225_1353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='engine',
            new_name='horsepower',
        ),
    ]
